name: Build and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        
    - name: Get modules
      run: yarn install
        
    - name: Build
      run: yarn build
      
    - name: Deploy to Scaleway
      run: aws s3 sync ./public s3://stock-options --delete --endpoint-url ${{ secrets.S3_ENDPOINT_URL }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.S3_REGION }}
        AWS_DEFAULT_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT_URL }}